### ISSUE TITLE
nv-dhcp-proxy must clean its socket file on exit

### ISSUE THREAD

**Issue by baude** [containers/netavark-dhcp-proxy#11]
We are not cleaning up the socket file on exit or control-c.

```
netavark-dhcp-proxy on  main [?⇡] is 📦 v0.1.0 via 🦀 v1.63.0 on ☁️  (us-west-2) on ☁️  bbaude@redhat.com(us-central1) 
❯ ./bin/netavark-proxy 
^C

netavark-dhcp-proxy on  main [?⇡] is 📦 v0.1.0 via 🦀 v1.63.0 on ☁️  (us-west-2) on ☁️  bbaude@redhat.com(us-central1) took 2s 
❯ ./bin/netavark-proxy 
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
```

**Comment by Jackbaude** [comment]
Rust has no native signal handling. This is only something that can be handled in c. We could either write the c bindings for this or use a library such as [signal-hook](https://docs.rs/signal-hook/latest/signal_hook/). Thoughts @baude?

**Comment by flouthoc** [comment]
@baude @Jackbaude are you looking for graceful shutdown ? @Jackbaude Using `signal_hook` is fine btw aardvark-dns uses it. But let me understand your use-case better then i can answer a better solution.

**Comment by Jackbaude** [comment]
@flouthoc Yes, we are looking for a graceful shutdown. The primary reason is to clean the socket on the exit. Currently, when the server is killed, it cannot clean the uds socket. On the next startup it then errors `Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }`. Additionally, I believe the cache memory should be cleaned on exit.

**Comment by flouthoc** [comment]
@Jackbaude Ah so I see that tokio is being used here if you can make the call to server ( which blocks ) a separate task inside `#[tokio::main]` for such cases tokio has a boilerplate for performing graceful shutdown, see: https://tokio.rs/tokio/topics/shutdown

* There are some third-party crates as well if you want easier integration https://github.com/Finomnis/tokio-graceful-shutdown
* Or use `tokio_signal` https://stackoverflow.com/a/53505771

`signal_hook` should also work as an alternative but I think you will have to move core server in a different thread and main blocks on signal processing which does the cleanup, this example shows exactly what i mean: https://docs.rs/signal-hook/latest/signal_hook/#a-complex-signal-handling-with-a-background-thread

If you think `signal_hook` method is easier to implement then I don't see any issues with using `signal_hook`.
