### ISSUE TITLE
bad error for uds permissions

### ISSUE THREAD

**Issue by baude** [containers/netavark-dhcp-proxy#38]
when trying to use a uds path that the user does not have permissions to, the error sucks

```
Error: transport error
Error: status: Internal, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
```

**Comment by Jackbaude** [comment]
I will look into this.

**Comment by Jackbaude** [comment]
@baude Can you give me an example where you see this problem happening? Including what you called?

**Comment by baude** [comment]
this was probably in the client.  closing
